name: Automated Preprocessing Heart Disease

on:
  push:
    paths:
      - heart_raw/**
      - preprocessing/automate_Jonathan-Regan.py

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pandas scikit-learn

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Jonathan-Regan.py

    - name: Commit preprocessing result
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add preprocessing/heart_preprocessing/heart_preprocessed.csv
        git commit -m "Update preprocessed dataset" || echo "No changes to commit"
        git push
